Uprev cos-gpu-installer to support new COS versions.
Also update WORKSPACE to resolve build failure. Failure had the
following error:

INFO: Call stack for the definition of repository 'package_bundle' which is a _dpkg_list (rule definition at /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/distroless/package_manager/dpkg.bzl:19:14):
- /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/distroless/package_manager/dpkg.bzl:74:3
- /workspace/WORKSPACE:173:1
ERROR: An error occurred during the fetch of repository 'package_bundle':
sequence element must be a string (got 'path'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.